export enum ErrorCodes {
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ALREDY_EXISTS = "USER_ALREDY_EXISTS",
  USER_CREATION_FAILED = "USER_CREATION_FAILED",
  USER_UPDATE_FAILED = "USER_UPDATE_FAILED",
  WRONG_CREDENTIALS = "WRONG_CREDENTIALS",
  NOT_AUTHENTICATED = "NOT_AUTHENTICATED",

  FILE_PARSING_FAILED = "FILE_PARSING_FAILED",
  FILE_EXTENSION_NOT_SUPPORTED = "FILE_EXTENSION_NOT_SUPPORTED",
  FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED",

  NXTE_CREATION_FAILED = "NXTE_CREATION_FAILED",
  NXTE_UPDATE_FAILED = "NXTE_UPDATE_FAILED",
  NXTE_DELETION_FAILED = "NXTE_DELETION_FAILED",

  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  GRAPHQL_PARSE_FAILED = "GRAPHQL_PARSE_FAILED",
  GRAPHQL_VALIDATION_FAILED = "GRAPHQL_VALIDATION_FAILED",
  PERSISTED_QUERY_NOT_FOUND = "PERSISTED_QUERY_NOT_FOUND",
  PERSISTED_QUERY_NOT_SUPPORTED = "PERSISTED_QUERY_NOT_SUPPORTED",
  BAD_USER_INPUT = "BAD_USER_INPUT",
  OPERATION_RESOLUTION_FAILURE = "OPERATION_RESOLUTION_FAILURE",
  BAD_REQUEST = "BAD_REQUEST",
}
